name: Test Deployment pipeline

on:
  push:
    branches:
      - pipeline
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP_CONDITION: ${{ github.event.commits == null || contains(github.event.commits[0].message, '#skip') }}

jobs:
  less_simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install backend dependancies
        run: |
          cd backend
          npm install
      - name: Install e2e dependancies
        run: |
          cd e2e
          npm install
      - name: Install frontend dependancies
        run: |
          cd frontend
          npm install
      - name: Check Style
        run: |
          cd backend
          npm run lint:backend
      - name: Check frontend Style
        run: |
          cd frontend
          npm run lint:frontend
      - name: Run backend tests
        run: |
          cd backend
          set -o pipefail
          NODE_ENV=test jest --verbose --runInBand
      - name: Run frontend tests
        run: |
          cd frontend
          npm run test:frontend
      - name: Build
        run: |
          cd backend
          npm run build:ui